title:              "Geeks' things Korea"
tagline:            "Kick it like a geek in Korea!"
email:              "your-email@example.com"
description:        "The things and things to do in Korea
                    Let’s just geek out for the another part that you could’ve missed."
author:             "habni"
baseurl:            "/"
url:                "https://geeksthingskorea.com"
locale:             "en_us"
thumbnail:          "/img/thumbnail.jpg"



# Social Profiles
twitter_username:   twitter_username
instagram_username: geekthingko
facebook_username:  GeekThingKo
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
