# Site settings
title: Geeks' things Korea
tagline: Kicking it like a geek in Korea!
description: "The things and things to do in Korea
Let’s just geek out for the another part that you could’ve missed."
url: "https://geeksthingskorea.com"
author:
  name: "habni"
  email: "habnipark@gmail.com"
  url: "https://geeksthingskorea.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
permalink: /:title
paginate: 8

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# disqus
disqus:
  shortname: geeks-things-korea
